import React from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
  faHouse,
  faScroll,
  faClipboard,
  faSitemap,
  faCity,
  faBuildingUser,
  faBuildingCircleCheck,
  faBuildingCircleArrowRight,
  faSliders,
  faGears,
  faScaleUnbalancedFlip,
  faBuilding,
  faMedal,
  faTimeline,
  faClipboardQuestion,
} from '@fortawesome/free-solid-svg-icons'
import { CNavGroup, CNavItem, CNavTitle } from '@coreui/react'

const _nav = [
  // ================= PANITIA ===============================
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/dashboard',
    icon: <FontAwesomeIcon icon={faHouse} size="lg" />,
    role: '0',
    index: 1,
  },
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/dashboard',
    icon: <FontAwesomeIcon icon={faHouse} size="lg" />,
    role: '4',
    index: 1,
  },
  {
    component: CNavTitle,
    name: 'Data Mahasiswa',
    role: '0',
    index: 2,
  },
  {
    component: CNavItem,
    name: 'Rekap CV',
    to: '/rekapCV',
    icon: <FontAwesomeIcon icon={faScroll} size="lg" />,
    role: '0',
    index: 3,
  },
  {
    component: CNavItem,
    name: 'Rekap Minat',
    to: '/rekapMinat',
    icon: <FontAwesomeIcon icon={faClipboard} size="lg" />,
    role: '0',
    index: 4,
  },
  {
    component: CNavGroup,
    name: 'Pemetaan Mahasiswa',
    to: '/pemetaan',
    icon: <FontAwesomeIcon icon={faSitemap} size="lg" />,
    role: '0',
    index: 5,
    items: [
      {
        component: CNavItem,
        name: 'Perangkingan Mahasiswa',
        to: '/pemetaan/perangkingan',
        index: 5.1,
      },
      {
        component: CNavItem,
        name: 'Finalisasi Pemetaan',
        to: '/pemetaan/finalisasi',
        index: 5.2,
      },
    ],
  },
  {
    component: CNavItem,
    name: 'Evaluasi Peserta',
    to: '/evaluasiPeserta',
    icon: <FontAwesomeIcon icon={faBuildingCircleCheck} size="lg" />,
    role: '0',
    index: 9,
  },
  {
    component: CNavTitle,
    name: 'Data Perusahaan',
    role: '0',
    index: 6,
  },
  {
    component: CNavItem,
    name: 'List Perusahaan',
    to: '/listPerusahaan',
    icon: <FontAwesomeIcon icon={faCity} size="lg" />,
    role: '0',
    index: 7,
  },
  {
    component: CNavItem,
    name: 'Pengajuan Perusahaan',
    to: '/pengajuanPerusahaan',
    icon: <FontAwesomeIcon icon={faBuildingUser} size="lg" />,
    role: '0',
    index: 8,
  },
  // {
  //   component: CNavItem,
  //   name: 'Feedback Perusahaan',
  //   to: '/feedbackPerusahaan',
  //   icon: <FontAwesomeIcon icon={faBuildingCircleArrowRight} size="lg" />,
  //   role: '0',
  //   index: 10,
  // },
  {
    component: CNavTitle,
    name: 'Lain - lain',
    role: '0',
    index: 11,
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Akun',
    to: '/pengelolaanAkun',
    icon: <FontAwesomeIcon icon={faSliders} size="lg" />,
    role: '0',
    index: 12,
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Cakupan Pekerjaan & Kompetensi',
    to: '/pengelolaanKompetensi',
    icon: <FontAwesomeIcon icon={faGears} size="lg" />,
    role: '0',
    index: 13,
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Bobot Kriteria Perangkingan',
    to: '/pengelolaanBobotKriteria',
    icon: <FontAwesomeIcon icon={faScaleUnbalancedFlip} size="lg" />,
    role: '0',
    index: 14,
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Kriteria Perusahaan',
    to: '/pengelolaanKriteriaPerusahaan',
    icon: <FontAwesomeIcon icon={faBuilding} size="lg" />,
    role: '0',
    index: 15,
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Aspek Penilaian Evaluasi',
    to: '/pengelolaanAspekPenilaianEvaluasi',
    icon: <FontAwesomeIcon icon={faMedal} size="lg" />,
    role: '0',
    index: 16,
  },
  // {
  //   component: CNavItem,
  //   name: 'Pengelolaan Pertanyaan Feedback',
  //   to: '/pengelolaanPertanyaanFeedback',
  //   icon: <FontAwesomeIcon icon={faClipboardQuestion} size="lg" />,
  //   role: '0',
  //   index: 17,
  // },
  {
    component: CNavItem,
    name: 'Pengelolaan Kegiatan',
    to: '/pengelolaanKegiatan',
    icon: <FontAwesomeIcon icon={faTimeline} size="lg" />,
    role: '0',
    index: 18,
  },

  // ================= Peserta ===============================
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/dashboard',
    icon: <FontAwesomeIcon icon={faHouse} size="lg" />,
    role: '1',
    index: 20,
  },
  {
    component: CNavTitle,
    name: 'Menu Mahasiswa',
    role: '1',
    index: 21,
  },
  {
    component: CNavItem,
    name: 'Biodata Mahasiswa',
    to: '/CV',
    icon: <FontAwesomeIcon icon={faScroll} size="lg" />,
    role: '1',
    index: 22,
  },
  {
    component: CNavItem,
    name: 'Pemilihan Perusahaan',
    to: '/pemilihanPerusahaan',
    icon: <FontAwesomeIcon icon={faBuildingUser} size="lg" />,
    role: '1',
    index: 23,
  },
  {
    component: CNavItem,
    name: 'Prerequisite Perusahaan',
    to: '/prerequisitePerusahaan',
    icon: <FontAwesomeIcon icon={faClipboard} size="lg" />,
    role: '1',
    index: 24,
  },
  {
    component: CNavItem,
    name: 'Hasil Pemetaan',
    to: '/hasilPemetaan',
    icon: <FontAwesomeIcon icon={faSitemap} size="lg" />,
    role: '1',
    index: 25,
  },
  {
    component: CNavItem,
    name: 'Hasil Evaluasi Perusahaan',
    to: '/hasilEvaluasiPerusahaan',
    icon: <FontAwesomeIcon icon={faBuildingCircleCheck} size="lg" />,
    role: '1',
    index: 26,
  },
  {
    component: CNavTitle,
    name: 'Lain - lain',
    role: '1',
    index: 27,
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Minat & Kompetensi',
    to: '/pengelolaanKompetensi',
    icon: <FontAwesomeIcon icon={faGears} size="lg" />,
    role: '1',
    index: 28,
  },

  // ================= Perusahaan ===============================
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/dashboard',
    icon: <FontAwesomeIcon icon={faHouse} size="lg" />,
    role: '2',
    index: 29,
  },
  {
    component: CNavTitle,
    name: 'Menu Perusahaan',
    role: '2',
    index: 30,
  },
  {
    component: CNavItem,
    name: 'Profil Perusahaan',
    to: '/profilPerusahaan',
    icon: <FontAwesomeIcon icon={faCity} size="lg" />,
    role: '2',
    index: 31,
  },
  {
    component: CNavItem,
    name: 'Formulir Kesediaan Perusahaan',
    to: '/formulirKesediaan',
    icon: <FontAwesomeIcon icon={faClipboard} size="lg" />,
    role: '2',
    index: 32,
  },
  {
    component: CNavItem,
    name: 'Biodata Mahasiswa',
    to: '/dataMahasiswa',
    icon: <FontAwesomeIcon icon={faScroll} size="lg" />,
    role: '2',
    index: 33,
  },
  {
    component: CNavItem,
    name: 'Formulir Evaluasi Peserta',
    to: '/dataEvaluasiPerusahaan',
    icon: <FontAwesomeIcon icon={faBuildingCircleCheck} size="lg" />,
    role: '2',
    index: 34,
  },
  {
    component: CNavItem,
    name: 'Formulir Feedback Pelaksanaan KP/PKL',
    to: '/dataFeedbackPerusahaan',
    icon: <FontAwesomeIcon icon={faBuildingCircleArrowRight} />,
    role: '2',
    index: 35,
  },
  {
    component: CNavTitle,
    name: 'Lain - lain',
    role: '2',
    index: 36,
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Cakupan Pekerjaan & Kompetensi',
    to: '/pengelolaanKompetensi',
    icon: <FontAwesomeIcon icon={faGears} size="lg" />,
    role: '2',
    index: 37,
  },

  // ================= Kaprodi ===============================
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/dashboard',
    icon: <FontAwesomeIcon icon={faHouse} size="lg" />,
    role: '3',
    index: 38,
  },
  {
    component: CNavTitle,
    name: 'Data Mahasiswa',
    role: '3',
    index: 46,
  },
  {
    component: CNavItem,
    name: 'Rekap CV',
    to: '/rekapCV',
    icon: <FontAwesomeIcon icon={faScroll} size="lg" />,
    role: '3',
    index: 47,
  },
  {
    component: CNavItem,
    name: 'Rekap Minat',
    to: '/rekapMinat',
    icon: <FontAwesomeIcon icon={faClipboard} size="lg" />,
    role: '3',
    index: 48,
  },
  {
    component: CNavItem,
    name: 'Hasil Pemetaan',
    to: '/hasilPemetaan',
    icon: <FontAwesomeIcon icon={faSitemap} size="lg" />,
    role: '3',
    index: 49,
  },
  {
    component: CNavItem,
    name: 'Evaluasi Peserta',
    to: '/evaluasiPeserta',
    icon: <FontAwesomeIcon icon={faBuildingCircleCheck} size="lg" />,
    role: '3',
    index: 41,
  },
  {
    component: CNavTitle,
    name: 'Data Perusahaan',
    role: '3',
    index: 39,
  },
  {
    component: CNavItem,
    name: 'List Perusahaan',
    to: '/listPerusahaan',
    icon: <FontAwesomeIcon icon={faCity} size="lg" />,
    role: '3',
    index: 40,
  },
  // {
  //   component: CNavItem,
  //   name: 'Feedback Perusahaan',
  //   to: '/feedbackPerusahaan',
  //   icon: <FontAwesomeIcon icon={faBuildingCircleArrowRight} />,
  //   role: '3',
  //   index: 42,
  // },
  {
    component: CNavTitle,
    name: 'Lain - lain',
    role: '3',
    index: 43,
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Akun',
    to: '/pengelolaanAkun',
    icon: <FontAwesomeIcon icon={faSliders} size="lg" />,
    role: '3',
    index: 45,
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Cakupan Pekerjaan & Kompetensi',
    to: '/pengelolaanKompetensi',
    icon: <FontAwesomeIcon icon={faGears} size="lg" />,
    role: '3',
    index: 44,
  },
  // MONITORING PELAKSANAAN
  {
    component: CNavTitle,
    name: 'Monitoring Pelaksanaan',
    role: '0',
    index: 50,
  },
  {
    component: CNavItem,
    name: 'Monitoring Dashboard',
    to: '/dashboardPanitia',
    icon: <FontAwesomeIcon icon={faScaleUnbalancedFlip} size="lg" />,
    role: '0',
    index: 51,
  },
  {
    component: CNavTitle,
    name: 'Pelaksanaan KP/PKL',
    role: '1',
    index: 52,
  },
  {
    component: CNavItem,
    name: 'Pemetaan Pembimbing Jurusan',
    to: '/pemetaanPembimbingJurusan',
    icon: <FontAwesomeIcon icon={faSliders}  size="lg" />,
    role: '0',
    index: 53,
  },
  {
    component: CNavItem,
    name: 'Daftar Peserta',
    to: '/daftarPeserta',
    icon: <FontAwesomeIcon icon={faSliders}  size="lg" />,
    role: '0',
    index: 54,
  },
  // {
  //   component: CNavItem,
  //   name: 'Rekap Monitoring',
  //   to: '/rekapMonitoring',
  //   icon: <FontAwesomeIcon icon={faClipboard} size="lg" />,
  //   role: '0',
  //   index: 55,
  // },
 
  //PESERTA
  {
    component: CNavItem,
    name: 'Dashboard Peserta',
    to: '/dashboardPeserta',
    icon: <FontAwesomeIcon icon={faScaleUnbalancedFlip} size="lg" />,
    role: '1',
    index: 57,
  },
  {
    component: CNavGroup,
    name: 'Dokumen Peserta',
    icon: <FontAwesomeIcon icon={faSitemap} size="lg" />,
    role: '1',
    index: 59,
    items: [
      {
        component: CNavItem,
        name: 'Rencana Penyelesaian Proyek',
        to: '/rencanaPenyelesaianProyek',
        index: 59.1
      },
      {
        component: CNavItem,
        name: 'Logbook',
        to: '/logbook',
        index: 59.2
      },
      {
        component: CNavItem,
        name: 'Self Assessment',
        to: '/selfAssessment',
        index: 59.3
      },
      {
        component: CNavItem,
        name: 'Dokumen Laporan',
        to: '/laporan',
        index: 59.4
      }
    ],
  },
  {
    component: CNavGroup,
    name: 'Pengelolaan Monitoring',
    icon: <FontAwesomeIcon icon={faSitemap} size="lg" />,
    role: '0',
    index: 56,
    items: [
      {
        component: CNavItem,
        name: 'Poin Penilaian Self Assessment',
        to: '/pembobotanSelfAssessment',
        index: 56.1
      },
      {
        component: CNavItem,
        name: 'Poin Penilaian Pembimbing Jurusan',
        to: '/pengelolaanPoinFormPembimbing',
        index: 56.2
      },
      {
        component: CNavItem,
        name: 'Pengelolaan Deadline',
        to: '/pengelolaanDeadline',
        index: 56.3
      },
    
    ],
  },
  //PEMBIMBING JURUSAN
  // {
  //   component: CNavItem,
  //   name: 'Dashboard Pembimbing',
  //   to: '/dashboardPembimbing',
  //   icon: <FontAwesomeIcon icon={faHouse} size="lg" />,
  //   role: '5',
  //   index: 60,
  // },

  // {
  //   component: CNavGroup,
  //   name: 'FITUR PEMBIMBING JURUSAN',
  //   icon: <FontAwesomeIcon icon={faSitemap} size="lg" />,
  //   role: '0',
  //   index: 61,
  //   items: [
  //     {
  //       component: CNavItem,
  //       name: 'Daftar Peserta',
  //       to: '/daftarPeserta',
  //       index: 61.1
  //     },
  //     {
  //       component: CNavItem,
  //       name: 'Penilaian Pembimbing Jurusan',
  //       to: '/logbook',
  //       index: 61.2
  //     },
  //     {
  //       component: CNavItem,
  //       name: 'Dokumen Self Assessment',
  //       to: '/formSelfAssessment',
  //       index: 61.3
  //     },
  //     {
  //       component: CNavItem,
  //       name: 'Dokumen Laporan',
  //       to: '/uploadLaporan',
  //       index: 61.4
  //     }
  //   ],
  // },
  {
    component: CNavItem,
    name: 'Rekap Dokumen Peserta',
    to: '/rekapDokumenPeserta',
    icon: <FontAwesomeIcon icon={faSliders}  size="lg" />,
    role: '0',
    index: 60,
  },
  {
    component: CNavItem,
    name: 'Rekap Penilaian Peserta',
    to: '/rekapPenilaianPeserta',
    icon: <FontAwesomeIcon icon={faSliders}  size="lg" />,
    role: '0',
    index: 62,
  },
  {
    component: CNavTitle,
    name: 'Monitoring Pelaksanaan',
    role: '4',
    index: 63,
  },
  {
    component: CNavItem,
    name: 'Monitoring Dashboard',
    to: '/dashboardPembimbing',
    icon: <FontAwesomeIcon icon={faScaleUnbalancedFlip} size="lg" />,
    role: '4',
    index: 64,
  },
  {
    component: CNavItem,
    name: 'Daftar Peserta',
    to: '/daftarPeserta',
    icon: <FontAwesomeIcon icon={faSliders}  size="lg" />,
    role: '4',
    index: 65,
  },
  {
    component: CNavItem,
    name: 'Rekap Dokumen Peserta',
    to: '/rekapDokumenPeserta',
    icon: <FontAwesomeIcon icon={faSliders}  size="lg" />,
    role: '4',
    index: 66,
  },
  {
    component: CNavItem,
    name: 'Rekap Penilaian Peserta',
    to: '/rekapPenilaianPeserta',
    icon: <FontAwesomeIcon icon={faSliders}  size="lg" />,
    role: '4',
    index: 67,
  },


]

export default _nav
